import { NavCollection } from '@models/interfaces/index';

export const routes: NavCollection = {
  components: [
    { title: 'Badge', route: '/components/badge' },
    { title: 'Button', route: '/components/button' },
    {
      title: 'Button Uploader',
      route: '/components/button-uploader',
    },
    { title: 'Calendar', route: '/components/calendar' },
    { title: 'Carousel', route: '/components/carousel' },
    { title: 'Charts', route: '/components/charts' },
    { title: 'Checkbox', route: '/components/checkbox' },
    { title: 'Chips', route: '/components/chips' },
    { title: 'Datatable', route: '/components/datatable' },
    { title: 'Divider', route: '/components/divider' },
    { title: 'Dropdown', route: '/components/dropdown' },
    { title: 'Fieldset', route: '/components/fieldset' },
    { title: 'Input', route: '/components/input' },
    { title: 'Input Number', route: '/components/input-number' },
    { title: 'Image', route: '/components/image' },
    { title: 'Image Uploader', route: '/components/image-uploader' },
    { title: 'Knob', route: '/components/knob' },
    { title: 'Message', route: '/components/message' },
    { title: 'Profile DropDown', route: '/components/profile-dropDown' },
    { title: 'Progress Bar', route: '/components/progress-bar' },
    { title: 'Radio Button', route: '/components/radioButton' },
    { title: 'Phone Number', route: '/components/phone-number' },
    { title: 'Rating', route: '/components/rating' },
    { title: 'Slider', route: '/components/slider' },
    { title: 'Skeleton', route: '/components/skeleton' },
    { title: 'Spinner', route: '/components/spinner' },
    { title: 'TabView', route: '/components/tabView' },
    { title: 'Toaster', route: '/components/toaster' },
  ],
  directives: [{ title: 'Directive', route: '/directives/directive' }],
  interceptors: [
    { title: 'Interceptors', route: '/interceptors/interceptorsTypes' },
  ],
  pipes: [],
  resolvers: [],
  services: [
    { title: 'Access Layer', route: '/services/access-layer' },
    { title: 'HttpCalls', route: '/services/httpCalls' },
    { title: 'Dynamic Dialog', route: '/services/dialog-services' },
    { title: 'Pipes', route: '/services/pipes' },
    { title: 'Display', route: '/services/display' },
    { title: 'Local-Storage', route: '/services/local-storage' },
  ],
  externalPackages: [
    { title: 'Flag Icons', route: '/external-packages/flag-icons' },
    { title: 'html2Canvas', route: '/external-packages/html2cnavas' },
    { title: 'I18n Translation', route: '/external-packages/i18n' },
  ],
  builder: [{ title: 'Builder', route: '/builder' }],
  seo: [
    { title: 'Emarsys', route: '/seo/emarsys' },
    { title: 'Inject Script Tag', route: '/seo/inject-script-tag' },
    { title: 'Link', route: '/seo/link' },
    { title: 'Meta Tags', route: '/seo/meta-tags' },
    { title: 'Page Title', route: '/seo/page-title' },
    { title: 'Tag Manager', route: '/seo/tag-manager' },
    {
      title: 'HotJar',
      route: '/seo/hotjar',
    },
  ],
  logger: [{ title: 'Logger', route: '/logger/logger' }],
  tutorial: [
    { title: 'Design Patterns', route: '/tutorial/design-patterns' },
    { title: 'SOLID', route: '/tutorial/solid' },
    { title: 'Web Performance', route: '/tutorial/web-performance' },
    { title: 'Configure Prettier', route: '/tutorial/configure-prettier' },
  ],
  configuration: [
    { title: 'Configure Prettier', route: '/configuration/configure-prettier' },
  ],
};
